[package]
name = "lute"
version = "0.0.0"
authors = ["Kyle Chen"]
edition = "2024"
rust-version = "1.88"
description = "Immutable maps and sets built from fixed entries"
documentation = "https://docs.rs/lute"
readme = "README.md"
repository = "https://github.com/astral4/lute"
license = "MIT OR Apache-2.0"
keywords = ["map", "phf", "set"]
categories = ["data-structures", "no-std"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
foldhash = { version = "0.2", default-features = false }
databake = { version = "0.2", optional = true }
proc-macro-crate = { version = "3", optional = true }
hashbrown = { version = "0.17", optional = true, default-features = false, features = ["default-hasher"] }
rand_core = { version = "0.10", optional = true, default-features = false }
rand_xoshiro = { version = "0.8", optional = true, default-features = false }

[features]
default = ["construct"]
construct = ["dep:hashbrown", "dep:rand_core", "dep:rand_xoshiro"]
codegen = ["construct", "dep:databake", "dep:proc-macro-crate"]

[dev-dependencies]
divan = "0.1"

[[bench]]
name = "bench"
harness = false
required-features = ["construct"]

[lints.rust]
async_fn_in_trait = "allow"
ffi_unwind_calls = "warn"
let_underscore_drop = "deny"
macro_use_extern_crate = "deny"
meta_variable_misuse = "deny"
missing_abi = "deny"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
non_ascii_idents = "forbid"
non_local_definitions = "warn"
nonstandard_style = { level = "deny", priority = 1 }
redundant_lifetimes = "deny"
rust_2018_idioms = { level = "deny", priority = 1 }
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unit_bindings = "deny"
unreachable_pub = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_macro_rules = "deny"
unused_qualifications = "deny"

[lints.rustdoc]
redundant_explicit_links = "allow"

[lints.clippy]
module_name_repetitions = { level = "allow", priority = 1 }
pedantic = "warn"
