[workspace]
resolver = "3"
members = ["crates/lute", "crates/lute_core", "crates/lute_macros", "crates/codegen_test"]

[workspace.package]
version = "0.1.0"
authors = ["Kyle Chen"]
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/astral4/lute"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
lute_core = { path = "crates/lute_core", version = "=0.1.0", default-features = false }
lute_macros = { path = "crates/lute_macros", version = "=0.1.0" }
databake = "0.2"
divan = "0.1"
foldhash = { version = "0.2", default-features = false }
hashbrown = { version = "0.17", default-features = false, features = ["default-hasher"] }
phf = "0.14"
phf_generator = "0.14"
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
rand_core = { version = "0.10", default-features = false }
rand_xoshiro = { version = "0.8", default-features = false }
syn = { version = "2", features = ["full"] }
trybuild = "1"

[workspace.lints.rust]
async_fn_in_trait = "allow"
ffi_unwind_calls = "warn"
let_underscore_drop = "deny"
macro_use_extern_crate = "deny"
meta_variable_misuse = "deny"
missing_abi = "deny"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
non_ascii_idents = "forbid"
non_local_definitions = "warn"
nonstandard_style = { level = "deny", priority = 1 }
redundant_lifetimes = "deny"
rust_2018_idioms = { level = "deny", priority = 1 }
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unit_bindings = "deny"
unreachable_pub = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_macro_rules = "deny"
unused_qualifications = "deny"

[workspace.lints.rustdoc]
redundant_explicit_links = "allow"

[workspace.lints.clippy]
module_name_repetitions = { level = "allow", priority = 1 }
pedantic = "warn"
